d <- read.csv("/home/sathvik/EC8/ML/Lab/Lab7/test.csv")
#folds <- createFolds(credit$default, k = 1338)
d1<-sample(d$expenses,x=1338,replace = T)
mean(d$expenses[d1])
d2<-sample(d$expenses,x=1338,replace = T)
mean(d$expenses[d2])
d3<-sample(d$expenses,x=1338,replace = T)
mean(d$expenses[d3])
mean(d$expenses)